### ISSUE TITLE
error when running the file

### ISSUE THREAD

**Issue by tofuboitofu** [OffensivePython/Saddam#19]
Traceback (most recent call last):
  File "./Saddam.py", line 321, in <module>
    main()
  File "./Saddam.py", line 309, in main
    Benchmark(ddos)
  File "./Saddam.py", line 156, in Benchmark
    recvd, sent = ddos.GetAmpSize(proto, soldier, domain)
  File "./Saddam.py", line 210, in GetAmpSize
    sock.sendto(packet, (soldier, PORT[proto]))
socket.gaierror: [Errno -2] Name or service not known

This is the error.

**Comment by AlessioScarlet** [comment]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Saddam.py", line 251, in __attack
    size, _ = self.GetAmpSize(proto, soldier, domain)
  File "Saddam.py", line 210, in GetAmpSize
    sock.sendto(packet, (soldier, PORT[proto]))
gaierror: [Errno -2] Name or service not known
```

Having this one...

**Comment by alessio-ds** [comment]
I am getting the same error.
"gai" stands for getaddressinfo, but I can't get where's the problem...


```
root@kali:~/Desktop/saddam# python Saddam.py benchmark -d dns.txt:google.com

           _____           __    __              
          / ___/____ _____/ /___/ /___ _____ ___ 
          \__ \/ __ `/ __  / __  / __ `/ __ `__ \
         ___/ / /_/ / /_/ / /_/ / /_/ / / / / / /
        /____/\__,_/\__,_/\__,_/\__,_/_/ /_/ /_/ 
        https://github.com/OffensivePython/Saddam
           https://twitter.com/OffensivePython

Protocol|  IP  Address  |     Amplification     |     Domain    
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "Saddam.py", line 321, in <module>
    main()
  File "Saddam.py", line 309, in main
    Benchmark(ddos)
  File "Saddam.py", line 156, in Benchmark
    recvd, sent = ddos.GetAmpSize(proto, soldier, domain)
  File "Saddam.py", line 210, in GetAmpSize
    sock.sendto(packet, (soldier, PORT[proto]))
socket.gaierror: [Errno -2] Name or service not known

```

**Comment by ilovedogs1235** [comment]
y'all dumb as hell
