### ISSUE TITLE
Benchmark issue

### ISSUE THREAD

**Issue by ghost** [OffensivePython/Saddam#7]
So i scan with nscan for NTP with the imported Monlist script using the stable version. 

Like this : ./nscan.py 0.range.0/0 -p123 --import=monlist:123 -n 2000 -o amp_ntp.txt --cooldown=10000,0.3

So i got my results in a text file but when i try to benchmark using saddam with pinject in the same folder like this : python Saddam.py benchmark -n ntp.txt 
i get these errors:

Traceback (most recent call last):
  File "Saddam.py", line 321, in <module>
    main()
  File "Saddam.py", line 309, in main
    Benchmark(ddos)
  File "Saddam.py", line 163, in Benchmark
    recvd, sent = ddos.GetAmpSize(proto, soldier)
  File "Saddam.py", line 198, in GetAmpSize
    sock.sendto(packet, (soldier, PORT[proto]))
socket.gaierror: [Errno -2] Name or service not known

**Comment by LevyHsu** [comment]
Not sure about the format of your output
But the list may looks like:
123.123.123.123
123.123.123.124
123.123.123.125
.....
Few ip address for your test purpose(Still valid yesterday):
122.252.176.60
150.242.254.27
173.228.231.214
(Don't be evil)
Also:
a ip address with a opening port 123 ≠ a server with NTP&monlist service

**Comment by ghost** [comment]
As you can see i used 
 ./nscan.py 0.range.0/0 -p123 --import=monlist:123 -n 2000 -o amp_ntp.txt --cooldown=10000,0.3
To get a big list of ip's with port 123 open running monlist.
So the problem could be that Nscan is not putting the results in the results.txt file correctly..?
